/*
 * This source file was generated by the Gradle 'init' task
 */
package kss.merkle;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        System.out.println("Kappa");
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
